/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentada);
  }
}(this, function(expect, ApiDocumentada) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentada.EventosApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventosApi', function() {
    describe('adhesionEvento', function() {
      it('should call adhesionEvento successfully', function(done) {
        //uncomment below and update the code to test adhesionEvento
        //instance.adhesionEvento(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createEvent', function() {
      it('should call createEvent successfully', function(done) {
        //uncomment below and update the code to test createEvent
        //instance.createEvent(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteEventById', function() {
      it('should call deleteEventById successfully', function(done) {
        //uncomment below and update the code to test deleteEventById
        //instance.deleteEventById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRequesEventoKafka', function() {
      it('should call deleteRequesEventoKafka successfully', function(done) {
        //uncomment below and update the code to test deleteRequesEventoKafka
        //instance.deleteRequesEventoKafka(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEventoById', function() {
      it('should call getEventoById successfully', function(done) {
        //uncomment below and update the code to test getEventoById
        //instance.getEventoById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEventoWithDonacionesById', function() {
      it('should call getEventoWithDonacionesById successfully', function(done) {
        //uncomment below and update the code to test getEventoWithDonacionesById
        //instance.getEventoWithDonacionesById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getEventoWithUsersById', function() {
      it('should call getEventoWithUsersById successfully', function(done) {
        //uncomment below and update the code to test getEventoWithUsersById
        //instance.getEventoWithUsersById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('insertDonacionesToEvento', function() {
      it('should call insertDonacionesToEvento successfully', function(done) {
        //uncomment below and update the code to test insertDonacionesToEvento
        //instance.insertDonacionesToEvento(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('insertUsersToEvento', function() {
      it('should call insertUsersToEvento successfully', function(done) {
        //uncomment below and update the code to test insertUsersToEvento
        //instance.insertUsersToEvento(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listEventos', function() {
      it('should call listEventos successfully', function(done) {
        //uncomment below and update the code to test listEventos
        //instance.listEventos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('newRequesEventoKafka', function() {
      it('should call newRequesEventoKafka successfully', function(done) {
        //uncomment below and update the code to test newRequesEventoKafka
        //instance.newRequesEventoKafka(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateEventoById', function() {
      it('should call updateEventoById successfully', function(done) {
        //uncomment below and update the code to test updateEventoById
        //instance.updateEventoById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
