/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Categoria from './model/Categoria';
import Donacion from './model/Donacion';
import DonacionList from './model/DonacionList';
import DonacionTransferencia from './model/DonacionTransferencia';
import Error from './model/Error';
import Evento from './model/Evento';
import EventoCategoria from './model/EventoCategoria';
import EventoDonacion from './model/EventoDonacion';
import EventoDonacionObjeto from './model/EventoDonacionObjeto';
import EventoDonacionReq from './model/EventoDonacionReq';
import EventoList from './model/EventoList';
import EventoListaDonacion from './model/EventoListaDonacion';
import EventoRol from './model/EventoRol';
import EventoUsersDto from './model/EventoUsersDto';
import EventoUsersListDto from './model/EventoUsersListDto';
import EventoUsuario from './model/EventoUsuario';
import Login from './model/Login';
import Rol from './model/Rol';
import Solicitud from './model/Solicitud';
import SolicitudCategoria from './model/SolicitudCategoria';
import SolicitudDonacion from './model/SolicitudDonacion';
import SolicitudError from './model/SolicitudError';
import Token from './model/Token';
import Transferencia from './model/Transferencia';
import Usuario from './model/Usuario';
import UsuarioList from './model/UsuarioList';
import DonacionesApi from './api/DonacionesApi';
import EventosApi from './api/EventosApi';
import SolicitudesApi from './api/SolicitudesApi';
import TransferenciasApi from './api/TransferenciasApi';
import UserApi from './api/UserApi';


/**
* Documentación de la API de ejemplo con Flask + gRPC.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiDocumentada = require('index'); // See note below*.
* var xxxSvc = new ApiDocumentada.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiDocumentada.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiDocumentada.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiDocumentada.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Categoria model constructor.
     * @property {module:model/Categoria}
     */
    Categoria,

    /**
     * The Donacion model constructor.
     * @property {module:model/Donacion}
     */
    Donacion,

    /**
     * The DonacionList model constructor.
     * @property {module:model/DonacionList}
     */
    DonacionList,

    /**
     * The DonacionTransferencia model constructor.
     * @property {module:model/DonacionTransferencia}
     */
    DonacionTransferencia,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Evento model constructor.
     * @property {module:model/Evento}
     */
    Evento,

    /**
     * The EventoCategoria model constructor.
     * @property {module:model/EventoCategoria}
     */
    EventoCategoria,

    /**
     * The EventoDonacion model constructor.
     * @property {module:model/EventoDonacion}
     */
    EventoDonacion,

    /**
     * The EventoDonacionObjeto model constructor.
     * @property {module:model/EventoDonacionObjeto}
     */
    EventoDonacionObjeto,

    /**
     * The EventoDonacionReq model constructor.
     * @property {module:model/EventoDonacionReq}
     */
    EventoDonacionReq,

    /**
     * The EventoList model constructor.
     * @property {module:model/EventoList}
     */
    EventoList,

    /**
     * The EventoListaDonacion model constructor.
     * @property {module:model/EventoListaDonacion}
     */
    EventoListaDonacion,

    /**
     * The EventoRol model constructor.
     * @property {module:model/EventoRol}
     */
    EventoRol,

    /**
     * The EventoUsersDto model constructor.
     * @property {module:model/EventoUsersDto}
     */
    EventoUsersDto,

    /**
     * The EventoUsersListDto model constructor.
     * @property {module:model/EventoUsersListDto}
     */
    EventoUsersListDto,

    /**
     * The EventoUsuario model constructor.
     * @property {module:model/EventoUsuario}
     */
    EventoUsuario,

    /**
     * The Login model constructor.
     * @property {module:model/Login}
     */
    Login,

    /**
     * The Rol model constructor.
     * @property {module:model/Rol}
     */
    Rol,

    /**
     * The Solicitud model constructor.
     * @property {module:model/Solicitud}
     */
    Solicitud,

    /**
     * The SolicitudCategoria model constructor.
     * @property {module:model/SolicitudCategoria}
     */
    SolicitudCategoria,

    /**
     * The SolicitudDonacion model constructor.
     * @property {module:model/SolicitudDonacion}
     */
    SolicitudDonacion,

    /**
     * The SolicitudError model constructor.
     * @property {module:model/SolicitudError}
     */
    SolicitudError,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The Transferencia model constructor.
     * @property {module:model/Transferencia}
     */
    Transferencia,

    /**
     * The Usuario model constructor.
     * @property {module:model/Usuario}
     */
    Usuario,

    /**
     * The UsuarioList model constructor.
     * @property {module:model/UsuarioList}
     */
    UsuarioList,

    /**
    * The DonacionesApi service constructor.
    * @property {module:api/DonacionesApi}
    */
    DonacionesApi,

    /**
    * The EventosApi service constructor.
    * @property {module:api/EventosApi}
    */
    EventosApi,

    /**
    * The SolicitudesApi service constructor.
    * @property {module:api/SolicitudesApi}
    */
    SolicitudesApi,

    /**
    * The TransferenciasApi service constructor.
    * @property {module:api/TransferenciasApi}
    */
    TransferenciasApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
