/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Donacion from './model/Donacion';
import DonacionList from './model/DonacionList';
import Error from './model/Error';
import Evento from './model/Evento';
import EventoList from './model/EventoList';
import Login from './model/Login';
import Rol from './model/Rol';
import Token from './model/Token';
import UsersListDto from './model/UsersListDto';
import Usuario from './model/Usuario';
import UsuarioList from './model/UsuarioList';
import DonacionesApi from './api/DonacionesApi';
import EventosApi from './api/EventosApi';
import UserApi from './api/UserApi';


/**
* Documentación de la API de ejemplo con Flask + gRPC.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiDocumentada = require('index'); // See note below*.
* var xxxSvc = new ApiDocumentada.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiDocumentada.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiDocumentada.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiDocumentada.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Donacion model constructor.
     * @property {module:model/Donacion}
     */
    Donacion,

    /**
     * The DonacionList model constructor.
     * @property {module:model/DonacionList}
     */
    DonacionList,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Evento model constructor.
     * @property {module:model/Evento}
     */
    Evento,

    /**
     * The EventoList model constructor.
     * @property {module:model/EventoList}
     */
    EventoList,

    /**
     * The Login model constructor.
     * @property {module:model/Login}
     */
    Login,

    /**
     * The Rol model constructor.
     * @property {module:model/Rol}
     */
    Rol,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The UsersListDto model constructor.
     * @property {module:model/UsersListDto}
     */
    UsersListDto,

    /**
     * The Usuario model constructor.
     * @property {module:model/Usuario}
     */
    Usuario,

    /**
     * The UsuarioList model constructor.
     * @property {module:model/UsuarioList}
     */
    UsuarioList,

    /**
    * The DonacionesApi service constructor.
    * @property {module:api/DonacionesApi}
    */
    DonacionesApi,

    /**
    * The EventosApi service constructor.
    * @property {module:api/EventosApi}
    */
    EventosApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
