/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AdhesionEventoKafka from './model/AdhesionEventoKafka';
import BorrarQueryGraphql from './model/BorrarQueryGraphql';
import BorrarVarGraphq from './model/BorrarVarGraphq';
import Categoria from './model/Categoria';
import Donacion from './model/Donacion';
import DonacionList from './model/DonacionList';
import DonacionTransferencia from './model/DonacionTransferencia';
import Error from './model/Error';
import Evento from './model/Evento';
import EventoBajaKafka from './model/EventoBajaKafka';
import EventoCategoria from './model/EventoCategoria';
import EventoDonacion from './model/EventoDonacion';
import EventoDonacionObjeto from './model/EventoDonacionObjeto';
import EventoDonacionReq from './model/EventoDonacionReq';
import EventoDonacionesDtoInforme from './model/EventoDonacionesDtoInforme';
import EventoDtoFiltro from './model/EventoDtoFiltro';
import EventoDtoInforme from './model/EventoDtoInforme';
import EventoKafka from './model/EventoKafka';
import EventoList from './model/EventoList';
import EventoListaDonacion from './model/EventoListaDonacion';
import EventoOrganizacionDto from './model/EventoOrganizacionDto';
import EventoRol from './model/EventoRol';
import EventoUsersDto from './model/EventoUsersDto';
import EventoUsersListDto from './model/EventoUsersListDto';
import EventoUsuario from './model/EventoUsuario';
import ExcelFileResponse from './model/ExcelFileResponse';
import FiltroDto from './model/FiltroDto';
import FiltroEvento from './model/FiltroEvento';
import FiltroSolicitudDetalleDto from './model/FiltroSolicitudDetalleDto';
import FiltrosGraphQLResponse from './model/FiltrosGraphQLResponse';
import InformeEventosDto from './model/InformeEventosDto';
import InformeParticipacionEventos from './model/InformeParticipacionEventos';
import InformeSolicitud from './model/InformeSolicitud';
import InformeSolicitudList from './model/InformeSolicitudList';
import ListaFiltrosDto from './model/ListaFiltrosDto';
import ListaValue from './model/ListaValue';
import Login from './model/Login';
import ResDataGraphql from './model/ResDataGraphql';
import Rol from './model/Rol';
import Solicitud from './model/Solicitud';
import SolicitudBaja from './model/SolicitudBaja';
import SolicitudCategoria from './model/SolicitudCategoria';
import SolicitudDonacion from './model/SolicitudDonacion';
import SolicitudError from './model/SolicitudError';
import SolicitudFiltronformeSolicitud from './model/SolicitudFiltronformeSolicitud';
import SolicitudGet from './model/SolicitudGet';
import SolicitudGetList from './model/SolicitudGetList';
import SolicitudGraphQLInformeEnvelope from './model/SolicitudGraphQLInformeEnvelope';
import SolicitudGraphQLResponse from './model/SolicitudGraphQLResponse';
import SolicitudOrganizacionDto from './model/SolicitudOrganizacionDto';
import SolicitudQueryInformeSolicitud from './model/SolicitudQueryInformeSolicitud';
import SolicitudVariablesInformeSolicitud from './model/SolicitudVariablesInformeSolicitud';
import SubirFilGraphql from './model/SubirFilGraphql';
import SubirQueryGraphql from './model/SubirQueryGraphql';
import SubirVarGraphql from './model/SubirVarGraphql';
import Token from './model/Token';
import TraerFiltrosGraphQLEnvelope from './model/TraerFiltrosGraphQLEnvelope';
import TraerFiltrosGraphqlDto from './model/TraerFiltrosGraphqlDto';
import TraerQueryGraphql from './model/TraerQueryGraphql';
import TraerVarGraphqlDto from './model/TraerVarGraphqlDto';
import Transferencia from './model/Transferencia';
import Usuario from './model/Usuario';
import UsuarioList from './model/UsuarioList';
import VoluntarioDto from './model/VoluntarioDto';
import VoluntarioEventoDto from './model/VoluntarioEventoDto';
import DonacionesApi from './api/DonacionesApi';
import EventosApi from './api/EventosApi';
import FiltrosApi from './api/FiltrosApi';
import SolicitudesApi from './api/SolicitudesApi';
import TransferenciasApi from './api/TransferenciasApi';
import UserApi from './api/UserApi';


/**
* Documentación de la API de ejemplo con Flask + gRPC.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiDocumentada = require('index'); // See note below*.
* var xxxSvc = new ApiDocumentada.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiDocumentada.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiDocumentada.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiDocumentada.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AdhesionEventoKafka model constructor.
     * @property {module:model/AdhesionEventoKafka}
     */
    AdhesionEventoKafka,

    /**
     * The BorrarQueryGraphql model constructor.
     * @property {module:model/BorrarQueryGraphql}
     */
    BorrarQueryGraphql,

    /**
     * The BorrarVarGraphq model constructor.
     * @property {module:model/BorrarVarGraphq}
     */
    BorrarVarGraphq,

    /**
     * The Categoria model constructor.
     * @property {module:model/Categoria}
     */
    Categoria,

    /**
     * The Donacion model constructor.
     * @property {module:model/Donacion}
     */
    Donacion,

    /**
     * The DonacionList model constructor.
     * @property {module:model/DonacionList}
     */
    DonacionList,

    /**
     * The DonacionTransferencia model constructor.
     * @property {module:model/DonacionTransferencia}
     */
    DonacionTransferencia,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Evento model constructor.
     * @property {module:model/Evento}
     */
    Evento,

    /**
     * The EventoBajaKafka model constructor.
     * @property {module:model/EventoBajaKafka}
     */
    EventoBajaKafka,

    /**
     * The EventoCategoria model constructor.
     * @property {module:model/EventoCategoria}
     */
    EventoCategoria,

    /**
     * The EventoDonacion model constructor.
     * @property {module:model/EventoDonacion}
     */
    EventoDonacion,

    /**
     * The EventoDonacionObjeto model constructor.
     * @property {module:model/EventoDonacionObjeto}
     */
    EventoDonacionObjeto,

    /**
     * The EventoDonacionReq model constructor.
     * @property {module:model/EventoDonacionReq}
     */
    EventoDonacionReq,

    /**
     * The EventoDonacionesDtoInforme model constructor.
     * @property {module:model/EventoDonacionesDtoInforme}
     */
    EventoDonacionesDtoInforme,

    /**
     * The EventoDtoFiltro model constructor.
     * @property {module:model/EventoDtoFiltro}
     */
    EventoDtoFiltro,

    /**
     * The EventoDtoInforme model constructor.
     * @property {module:model/EventoDtoInforme}
     */
    EventoDtoInforme,

    /**
     * The EventoKafka model constructor.
     * @property {module:model/EventoKafka}
     */
    EventoKafka,

    /**
     * The EventoList model constructor.
     * @property {module:model/EventoList}
     */
    EventoList,

    /**
     * The EventoListaDonacion model constructor.
     * @property {module:model/EventoListaDonacion}
     */
    EventoListaDonacion,

    /**
     * The EventoOrganizacionDto model constructor.
     * @property {module:model/EventoOrganizacionDto}
     */
    EventoOrganizacionDto,

    /**
     * The EventoRol model constructor.
     * @property {module:model/EventoRol}
     */
    EventoRol,

    /**
     * The EventoUsersDto model constructor.
     * @property {module:model/EventoUsersDto}
     */
    EventoUsersDto,

    /**
     * The EventoUsersListDto model constructor.
     * @property {module:model/EventoUsersListDto}
     */
    EventoUsersListDto,

    /**
     * The EventoUsuario model constructor.
     * @property {module:model/EventoUsuario}
     */
    EventoUsuario,

    /**
     * The ExcelFileResponse model constructor.
     * @property {module:model/ExcelFileResponse}
     */
    ExcelFileResponse,

    /**
     * The FiltroDto model constructor.
     * @property {module:model/FiltroDto}
     */
    FiltroDto,

    /**
     * The FiltroEvento model constructor.
     * @property {module:model/FiltroEvento}
     */
    FiltroEvento,

    /**
     * The FiltroSolicitudDetalleDto model constructor.
     * @property {module:model/FiltroSolicitudDetalleDto}
     */
    FiltroSolicitudDetalleDto,

    /**
     * The FiltrosGraphQLResponse model constructor.
     * @property {module:model/FiltrosGraphQLResponse}
     */
    FiltrosGraphQLResponse,

    /**
     * The InformeEventosDto model constructor.
     * @property {module:model/InformeEventosDto}
     */
    InformeEventosDto,

    /**
     * The InformeParticipacionEventos model constructor.
     * @property {module:model/InformeParticipacionEventos}
     */
    InformeParticipacionEventos,

    /**
     * The InformeSolicitud model constructor.
     * @property {module:model/InformeSolicitud}
     */
    InformeSolicitud,

    /**
     * The InformeSolicitudList model constructor.
     * @property {module:model/InformeSolicitudList}
     */
    InformeSolicitudList,

    /**
     * The ListaFiltrosDto model constructor.
     * @property {module:model/ListaFiltrosDto}
     */
    ListaFiltrosDto,

    /**
     * The ListaValue model constructor.
     * @property {module:model/ListaValue}
     */
    ListaValue,

    /**
     * The Login model constructor.
     * @property {module:model/Login}
     */
    Login,

    /**
     * The ResDataGraphql model constructor.
     * @property {module:model/ResDataGraphql}
     */
    ResDataGraphql,

    /**
     * The Rol model constructor.
     * @property {module:model/Rol}
     */
    Rol,

    /**
     * The Solicitud model constructor.
     * @property {module:model/Solicitud}
     */
    Solicitud,

    /**
     * The SolicitudBaja model constructor.
     * @property {module:model/SolicitudBaja}
     */
    SolicitudBaja,

    /**
     * The SolicitudCategoria model constructor.
     * @property {module:model/SolicitudCategoria}
     */
    SolicitudCategoria,

    /**
     * The SolicitudDonacion model constructor.
     * @property {module:model/SolicitudDonacion}
     */
    SolicitudDonacion,

    /**
     * The SolicitudError model constructor.
     * @property {module:model/SolicitudError}
     */
    SolicitudError,

    /**
     * The SolicitudFiltronformeSolicitud model constructor.
     * @property {module:model/SolicitudFiltronformeSolicitud}
     */
    SolicitudFiltronformeSolicitud,

    /**
     * The SolicitudGet model constructor.
     * @property {module:model/SolicitudGet}
     */
    SolicitudGet,

    /**
     * The SolicitudGetList model constructor.
     * @property {module:model/SolicitudGetList}
     */
    SolicitudGetList,

    /**
     * The SolicitudGraphQLInformeEnvelope model constructor.
     * @property {module:model/SolicitudGraphQLInformeEnvelope}
     */
    SolicitudGraphQLInformeEnvelope,

    /**
     * The SolicitudGraphQLResponse model constructor.
     * @property {module:model/SolicitudGraphQLResponse}
     */
    SolicitudGraphQLResponse,

    /**
     * The SolicitudOrganizacionDto model constructor.
     * @property {module:model/SolicitudOrganizacionDto}
     */
    SolicitudOrganizacionDto,

    /**
     * The SolicitudQueryInformeSolicitud model constructor.
     * @property {module:model/SolicitudQueryInformeSolicitud}
     */
    SolicitudQueryInformeSolicitud,

    /**
     * The SolicitudVariablesInformeSolicitud model constructor.
     * @property {module:model/SolicitudVariablesInformeSolicitud}
     */
    SolicitudVariablesInformeSolicitud,

    /**
     * The SubirFilGraphql model constructor.
     * @property {module:model/SubirFilGraphql}
     */
    SubirFilGraphql,

    /**
     * The SubirQueryGraphql model constructor.
     * @property {module:model/SubirQueryGraphql}
     */
    SubirQueryGraphql,

    /**
     * The SubirVarGraphql model constructor.
     * @property {module:model/SubirVarGraphql}
     */
    SubirVarGraphql,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The TraerFiltrosGraphQLEnvelope model constructor.
     * @property {module:model/TraerFiltrosGraphQLEnvelope}
     */
    TraerFiltrosGraphQLEnvelope,

    /**
     * The TraerFiltrosGraphqlDto model constructor.
     * @property {module:model/TraerFiltrosGraphqlDto}
     */
    TraerFiltrosGraphqlDto,

    /**
     * The TraerQueryGraphql model constructor.
     * @property {module:model/TraerQueryGraphql}
     */
    TraerQueryGraphql,

    /**
     * The TraerVarGraphqlDto model constructor.
     * @property {module:model/TraerVarGraphqlDto}
     */
    TraerVarGraphqlDto,

    /**
     * The Transferencia model constructor.
     * @property {module:model/Transferencia}
     */
    Transferencia,

    /**
     * The Usuario model constructor.
     * @property {module:model/Usuario}
     */
    Usuario,

    /**
     * The UsuarioList model constructor.
     * @property {module:model/UsuarioList}
     */
    UsuarioList,

    /**
     * The VoluntarioDto model constructor.
     * @property {module:model/VoluntarioDto}
     */
    VoluntarioDto,

    /**
     * The VoluntarioEventoDto model constructor.
     * @property {module:model/VoluntarioEventoDto}
     */
    VoluntarioEventoDto,

    /**
    * The DonacionesApi service constructor.
    * @property {module:api/DonacionesApi}
    */
    DonacionesApi,

    /**
    * The EventosApi service constructor.
    * @property {module:api/EventosApi}
    */
    EventosApi,

    /**
    * The FiltrosApi service constructor.
    * @property {module:api/FiltrosApi}
    */
    FiltrosApi,

    /**
    * The SolicitudesApi service constructor.
    * @property {module:api/SolicitudesApi}
    */
    SolicitudesApi,

    /**
    * The TransferenciasApi service constructor.
    * @property {module:api/TransferenciasApi}
    */
    TransferenciasApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
