/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Donacion from '../model/Donacion';
import DonacionList from '../model/DonacionList';
import Error from '../model/Error';

/**
* Donaciones service.
* @module api/DonacionesApi
* @version 1.0
*/
export default class DonacionesApi {

    /**
    * Constructs a new DonacionesApi. 
    * @alias module:api/DonacionesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createDonation operation.
     * @callback module:api/DonacionesApi~createDonationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Donacion} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Insertar una nueva donacion
     * @param {module:model/Donacion} payload 
     * @param {module:api/DonacionesApi~createDonationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Donacion}
     */
    createDonation(payload, callback) {
      let postBody = payload;
      // verify the required parameter 'payload' is set
      if (payload === undefined || payload === null) {
        throw new Error("Missing the required parameter 'payload' when calling createDonation");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Donacion;
      return this.apiClient.callApi(
        '/donacion/new', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteDonationById operation.
     * @callback module:api/DonacionesApi~deleteDonationByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Donacion} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Eliminar donacion
     * @param {Number} id 
     * @param {module:api/DonacionesApi~deleteDonationByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Donacion}
     */
    deleteDonationById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteDonationById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Donacion;
      return this.apiClient.callApi(
        '/donacion/delete/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getDonationById operation.
     * @callback module:api/DonacionesApi~getDonationByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Donacion} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtener Donacion
     * @param {Number} id 
     * @param {module:api/DonacionesApi~getDonationByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Donacion}
     */
    getDonationById(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getDonationById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Donacion;
      return this.apiClient.callApi(
        '/donacion/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listDonations operation.
     * @callback module:api/DonacionesApi~listDonationsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DonacionList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtener todos las donaciones
     * @param {module:api/DonacionesApi~listDonationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DonacionList}
     */
    listDonations(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = DonacionList;
      return this.apiClient.callApi(
        '/donacion/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateDonationById operation.
     * @callback module:api/DonacionesApi~updateDonationByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Donacion} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Actualizar un donacion
     * @param {Number} id 
     * @param {module:model/Donacion} payload 
     * @param {module:api/DonacionesApi~updateDonationByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Donacion}
     */
    updateDonationById(id, payload, callback) {
      let postBody = payload;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateDonationById");
      }
      // verify the required parameter 'payload' is set
      if (payload === undefined || payload === null) {
        throw new Error("Missing the required parameter 'payload' when calling updateDonationById");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Donacion;
      return this.apiClient.callApi(
        '/donacion/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
