/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import ONG from '../model/ONG';
import OrgIds from '../model/OrgIds';
import Presidente from '../model/Presidente';

/**
* Soap service.
* @module api/SoapApi
* @version 1.0
*/
export default class SoapApi {

    /**
    * Constructs a new SoapApi. 
    * @alias module:api/SoapApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the postOngsSoap operation.
     * @callback module:api/SoapApi~postOngsSoapCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ONG>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Consultar datos de ONGs por IDs (SOAP)
     * @param {module:model/OrgIds} payload 
     * @param {module:api/SoapApi~postOngsSoapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ONG>}
     */
    postOngsSoap(payload, callback) {
      let postBody = payload;
      // verify the required parameter 'payload' is set
      if (payload === undefined || payload === null) {
        throw new Error("Missing the required parameter 'payload' when calling postOngsSoap");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [ONG];
      return this.apiClient.callApi(
        '/soap/ongs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postPresidentesSoap operation.
     * @callback module:api/SoapApi~postPresidentesSoapCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Presidente>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Consultar datos de Presidentes por IDs (SOAP)
     * @param {module:model/OrgIds} payload 
     * @param {module:api/SoapApi~postPresidentesSoapCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Presidente>}
     */
    postPresidentesSoap(payload, callback) {
      let postBody = payload;
      // verify the required parameter 'payload' is set
      if (payload === undefined || payload === null) {
        throw new Error("Missing the required parameter 'payload' when calling postPresidentesSoap");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [Presidente];
      return this.apiClient.callApi(
        '/soap/presidentes', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
