/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VoluntarioDto from './VoluntarioDto';

/**
 * The AdhesionEventoKafka model module.
 * @module model/AdhesionEventoKafka
 * @version 1.0
 */
class AdhesionEventoKafka {
    /**
     * Constructs a new <code>AdhesionEventoKafka</code>.
     * @alias module:model/AdhesionEventoKafka
     * @param idEvento {String} 
     * @param voluntario {module:model/VoluntarioDto} 
     */
    constructor(idEvento, voluntario) { 
        
        AdhesionEventoKafka.initialize(this, idEvento, voluntario);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, idEvento, voluntario) { 
        obj['id_evento'] = idEvento;
        obj['voluntario'] = voluntario;
    }

    /**
     * Constructs a <code>AdhesionEventoKafka</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AdhesionEventoKafka} obj Optional instance to populate.
     * @return {module:model/AdhesionEventoKafka} The populated <code>AdhesionEventoKafka</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdhesionEventoKafka();

            if (data.hasOwnProperty('id_evento')) {
                obj['id_evento'] = ApiClient.convertToType(data['id_evento'], 'String');
            }
            if (data.hasOwnProperty('voluntario')) {
                obj['voluntario'] = VoluntarioDto.constructFromObject(data['voluntario']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AdhesionEventoKafka</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AdhesionEventoKafka</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AdhesionEventoKafka.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id_evento'] && !(typeof data['id_evento'] === 'string' || data['id_evento'] instanceof String)) {
            throw new Error("Expected the field `id_evento` to be a primitive type in the JSON string but got " + data['id_evento']);
        }
        // validate the optional field `voluntario`
        if (data['voluntario']) { // data not null
          VoluntarioDto.validateJSON(data['voluntario']);
        }

        return true;
    }


}

AdhesionEventoKafka.RequiredProperties = ["id_evento", "voluntario"];

/**
 * @member {String} id_evento
 */
AdhesionEventoKafka.prototype['id_evento'] = undefined;

/**
 * @member {module:model/VoluntarioDto} voluntario
 */
AdhesionEventoKafka.prototype['voluntario'] = undefined;






export default AdhesionEventoKafka;

