/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BorrarVarGraphq model module.
 * @module model/BorrarVarGraphq
 * @version 1.0
 */
class BorrarVarGraphq {
    /**
     * Constructs a new <code>BorrarVarGraphq</code>.
     * @alias module:model/BorrarVarGraphq
     * @param id {Number} 
     */
    constructor(id) { 
        
        BorrarVarGraphq.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>BorrarVarGraphq</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BorrarVarGraphq} obj Optional instance to populate.
     * @return {module:model/BorrarVarGraphq} The populated <code>BorrarVarGraphq</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BorrarVarGraphq();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BorrarVarGraphq</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BorrarVarGraphq</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BorrarVarGraphq.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

BorrarVarGraphq.RequiredProperties = ["id"];

/**
 * @member {Number} id
 */
BorrarVarGraphq.prototype['id'] = undefined;






export default BorrarVarGraphq;

