/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Categoria model module.
 * @module model/Categoria
 * @version 1.0
 */
class Categoria {
    /**
     * Constructs a new <code>Categoria</code>.
     * @alias module:model/Categoria
     * @param descripcion {String} 
     * @param id {Number} 
     */
    constructor(descripcion, id) { 
        
        Categoria.initialize(this, descripcion, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, descripcion, id) { 
        obj['descripcion'] = descripcion;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>Categoria</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Categoria} obj Optional instance to populate.
     * @return {module:model/Categoria} The populated <code>Categoria</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Categoria();

            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Categoria</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Categoria</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Categoria.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['descripcion'] && !(typeof data['descripcion'] === 'string' || data['descripcion'] instanceof String)) {
            throw new Error("Expected the field `descripcion` to be a primitive type in the JSON string but got " + data['descripcion']);
        }

        return true;
    }


}

Categoria.RequiredProperties = ["descripcion", "id"];

/**
 * @member {String} descripcion
 */
Categoria.prototype['descripcion'] = undefined;

/**
 * @member {Number} id
 */
Categoria.prototype['id'] = undefined;






export default Categoria;

