/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DonacionTransferencia model module.
 * @module model/DonacionTransferencia
 * @version 1.0
 */
class DonacionTransferencia {
    /**
     * Constructs a new <code>DonacionTransferencia</code>.
     * @alias module:model/DonacionTransferencia
     * @param categoria {String} 
     * @param descripcion {String} 
     */
    constructor(categoria, descripcion) { 
        
        DonacionTransferencia.initialize(this, categoria, descripcion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, categoria, descripcion) { 
        obj['categoria'] = categoria;
        obj['descripcion'] = descripcion;
    }

    /**
     * Constructs a <code>DonacionTransferencia</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DonacionTransferencia} obj Optional instance to populate.
     * @return {module:model/DonacionTransferencia} The populated <code>DonacionTransferencia</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DonacionTransferencia();

            if (data.hasOwnProperty('categoria')) {
                obj['categoria'] = ApiClient.convertToType(data['categoria'], 'String');
            }
            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('cantidad')) {
                obj['cantidad'] = ApiClient.convertToType(data['cantidad'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DonacionTransferencia</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DonacionTransferencia</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DonacionTransferencia.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['categoria'] && !(typeof data['categoria'] === 'string' || data['categoria'] instanceof String)) {
            throw new Error("Expected the field `categoria` to be a primitive type in the JSON string but got " + data['categoria']);
        }
        // ensure the json data is a string
        if (data['descripcion'] && !(typeof data['descripcion'] === 'string' || data['descripcion'] instanceof String)) {
            throw new Error("Expected the field `descripcion` to be a primitive type in the JSON string but got " + data['descripcion']);
        }

        return true;
    }


}

DonacionTransferencia.RequiredProperties = ["categoria", "descripcion"];

/**
 * @member {String} categoria
 */
DonacionTransferencia.prototype['categoria'] = undefined;

/**
 * @member {String} descripcion
 */
DonacionTransferencia.prototype['descripcion'] = undefined;

/**
 * @member {Number} cantidad
 */
DonacionTransferencia.prototype['cantidad'] = undefined;






export default DonacionTransferencia;

