/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DonacionesListDto model module.
 * @module model/DonacionesListDto
 * @version 1.0
 */
class DonacionesListDto {
    /**
     * Constructs a new <code>DonacionesListDto</code>.
     * @alias module:model/DonacionesListDto
     * @param cantDonaciones {Number} 
     * @param donacionId {Array.<Number>} Lista de IDs de las donaciones
     */
    constructor(cantDonaciones, donacionId) { 
        
        DonacionesListDto.initialize(this, cantDonaciones, donacionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cantDonaciones, donacionId) { 
        obj['cantDonaciones'] = cantDonaciones;
        obj['donacionId'] = donacionId;
    }

    /**
     * Constructs a <code>DonacionesListDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DonacionesListDto} obj Optional instance to populate.
     * @return {module:model/DonacionesListDto} The populated <code>DonacionesListDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DonacionesListDto();

            if (data.hasOwnProperty('cantDonaciones')) {
                obj['cantDonaciones'] = ApiClient.convertToType(data['cantDonaciones'], 'Number');
            }
            if (data.hasOwnProperty('donacionId')) {
                obj['donacionId'] = ApiClient.convertToType(data['donacionId'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DonacionesListDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DonacionesListDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DonacionesListDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['donacionId'])) {
            throw new Error("Expected the field `donacionId` to be an array in the JSON data but got " + data['donacionId']);
        }

        return true;
    }


}

DonacionesListDto.RequiredProperties = ["cantDonaciones", "donacionId"];

/**
 * @member {Number} cantDonaciones
 */
DonacionesListDto.prototype['cantDonaciones'] = undefined;

/**
 * Lista de IDs de las donaciones
 * @member {Array.<Number>} donacionId
 */
DonacionesListDto.prototype['donacionId'] = undefined;






export default DonacionesListDto;

