/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventoKafka model module.
 * @module model/EventoKafka
 * @version 1.0
 */
class EventoKafka {
    /**
     * Constructs a new <code>EventoKafka</code>.
     * @alias module:model/EventoKafka
     * @param idOrganizacion {String} 
     * @param idEvento {String} 
     * @param nombre {String} 
     * @param descripcion {String} 
     * @param fecha {Date} 
     */
    constructor(idOrganizacion, idEvento, nombre, descripcion, fecha) { 
        
        EventoKafka.initialize(this, idOrganizacion, idEvento, nombre, descripcion, fecha);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, idOrganizacion, idEvento, nombre, descripcion, fecha) { 
        obj['id_organizacion'] = idOrganizacion;
        obj['id_evento'] = idEvento;
        obj['nombre'] = nombre;
        obj['descripcion'] = descripcion;
        obj['fecha'] = fecha;
    }

    /**
     * Constructs a <code>EventoKafka</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventoKafka} obj Optional instance to populate.
     * @return {module:model/EventoKafka} The populated <code>EventoKafka</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventoKafka();

            if (data.hasOwnProperty('id_organizacion')) {
                obj['id_organizacion'] = ApiClient.convertToType(data['id_organizacion'], 'String');
            }
            if (data.hasOwnProperty('id_evento')) {
                obj['id_evento'] = ApiClient.convertToType(data['id_evento'], 'String');
            }
            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('fecha')) {
                obj['fecha'] = ApiClient.convertToType(data['fecha'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventoKafka</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventoKafka</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventoKafka.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id_organizacion'] && !(typeof data['id_organizacion'] === 'string' || data['id_organizacion'] instanceof String)) {
            throw new Error("Expected the field `id_organizacion` to be a primitive type in the JSON string but got " + data['id_organizacion']);
        }
        // ensure the json data is a string
        if (data['id_evento'] && !(typeof data['id_evento'] === 'string' || data['id_evento'] instanceof String)) {
            throw new Error("Expected the field `id_evento` to be a primitive type in the JSON string but got " + data['id_evento']);
        }
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }
        // ensure the json data is a string
        if (data['descripcion'] && !(typeof data['descripcion'] === 'string' || data['descripcion'] instanceof String)) {
            throw new Error("Expected the field `descripcion` to be a primitive type in the JSON string but got " + data['descripcion']);
        }

        return true;
    }


}

EventoKafka.RequiredProperties = ["id_organizacion", "id_evento", "nombre", "descripcion", "fecha"];

/**
 * @member {String} id_organizacion
 */
EventoKafka.prototype['id_organizacion'] = undefined;

/**
 * @member {String} id_evento
 */
EventoKafka.prototype['id_evento'] = undefined;

/**
 * @member {String} nombre
 */
EventoKafka.prototype['nombre'] = undefined;

/**
 * @member {String} descripcion
 */
EventoKafka.prototype['descripcion'] = undefined;

/**
 * @member {Date} fecha
 */
EventoKafka.prototype['fecha'] = undefined;






export default EventoKafka;

