/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventoDonacionObjeto from './EventoDonacionObjeto';

/**
 * The EventoDonacion model module.
 * @module model/EventoDonacion
 * @version 1.0
 */
class EventoDonacion {
    /**
     * Constructs a new <code>EventoDonacion</code>.
     * @alias module:model/EventoDonacion
     * @param donacion {module:model/EventoDonacionObjeto} 
     * @param cantidad {Number} 
     */
    constructor(donacion, cantidad) { 
        
        EventoDonacion.initialize(this, donacion, cantidad);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, donacion, cantidad) { 
        obj['donacion'] = donacion;
        obj['cantidad'] = cantidad;
    }

    /**
     * Constructs a <code>EventoDonacion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventoDonacion} obj Optional instance to populate.
     * @return {module:model/EventoDonacion} The populated <code>EventoDonacion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventoDonacion();

            if (data.hasOwnProperty('donacion')) {
                obj['donacion'] = EventoDonacionObjeto.constructFromObject(data['donacion']);
            }
            if (data.hasOwnProperty('cantidad')) {
                obj['cantidad'] = ApiClient.convertToType(data['cantidad'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventoDonacion</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventoDonacion</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventoDonacion.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `donacion`
        if (data['donacion']) { // data not null
          EventoDonacionObjeto.validateJSON(data['donacion']);
        }

        return true;
    }


}

EventoDonacion.RequiredProperties = ["donacion", "cantidad"];

/**
 * @member {module:model/EventoDonacionObjeto} donacion
 */
EventoDonacion.prototype['donacion'] = undefined;

/**
 * @member {Number} cantidad
 */
EventoDonacion.prototype['cantidad'] = undefined;






export default EventoDonacion;

