/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventoDonacion model module.
 * @module model/EventoDonacion
 * @version 1.0
 */
class EventoDonacion {
    /**
     * Constructs a new <code>EventoDonacion</code>.
     * @alias module:model/EventoDonacion
     * @param cantidad {Number} 
     */
    constructor(cantidad) { 
        
        EventoDonacion.initialize(this, cantidad);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cantidad) { 
        obj['cantidad'] = cantidad;
    }

    /**
     * Constructs a <code>EventoDonacion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventoDonacion} obj Optional instance to populate.
     * @return {module:model/EventoDonacion} The populated <code>EventoDonacion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventoDonacion();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('cantidad')) {
                obj['cantidad'] = ApiClient.convertToType(data['cantidad'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventoDonacion</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventoDonacion</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventoDonacion.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['descripcion'] && !(typeof data['descripcion'] === 'string' || data['descripcion'] instanceof String)) {
            throw new Error("Expected the field `descripcion` to be a primitive type in the JSON string but got " + data['descripcion']);
        }

        return true;
    }


}

EventoDonacion.RequiredProperties = ["cantidad"];

/**
 * @member {Number} id
 */
EventoDonacion.prototype['id'] = undefined;

/**
 * @member {String} descripcion
 */
EventoDonacion.prototype['descripcion'] = undefined;

/**
 * @member {Number} cantidad
 */
EventoDonacion.prototype['cantidad'] = undefined;






export default EventoDonacion;

