/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventoDonacionReq model module.
 * @module model/EventoDonacionReq
 * @version 1.0
 */
class EventoDonacionReq {
    /**
     * Constructs a new <code>EventoDonacionReq</code>.
     * @alias module:model/EventoDonacionReq
     * @param cantidad {Number} 
     * @param donacionId {Number} 
     */
    constructor(cantidad, donacionId) { 
        
        EventoDonacionReq.initialize(this, cantidad, donacionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cantidad, donacionId) { 
        obj['cantidad'] = cantidad;
        obj['donacionId'] = donacionId;
    }

    /**
     * Constructs a <code>EventoDonacionReq</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventoDonacionReq} obj Optional instance to populate.
     * @return {module:model/EventoDonacionReq} The populated <code>EventoDonacionReq</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventoDonacionReq();

            if (data.hasOwnProperty('cantidad')) {
                obj['cantidad'] = ApiClient.convertToType(data['cantidad'], 'Number');
            }
            if (data.hasOwnProperty('donacionId')) {
                obj['donacionId'] = ApiClient.convertToType(data['donacionId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventoDonacionReq</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventoDonacionReq</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventoDonacionReq.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

EventoDonacionReq.RequiredProperties = ["cantidad", "donacionId"];

/**
 * @member {Number} cantidad
 */
EventoDonacionReq.prototype['cantidad'] = undefined;

/**
 * @member {Number} donacionId
 */
EventoDonacionReq.prototype['donacionId'] = undefined;






export default EventoDonacionReq;

