/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Evento from './Evento';

/**
 * The EventoList model module.
 * @module model/EventoList
 * @version 1.0
 */
class EventoList {
    /**
     * Constructs a new <code>EventoList</code>.
     * @alias module:model/EventoList
     */
    constructor() { 
        
        EventoList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EventoList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventoList} obj Optional instance to populate.
     * @return {module:model/EventoList} The populated <code>EventoList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventoList();

            if (data.hasOwnProperty('eventos')) {
                obj['eventos'] = ApiClient.convertToType(data['eventos'], [Evento]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventoList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventoList</code>.
     */
    static validateJSON(data) {
        if (data['eventos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['eventos'])) {
                throw new Error("Expected the field `eventos` to be an array in the JSON data but got " + data['eventos']);
            }
            // validate the optional field `eventos` (array)
            for (const item of data['eventos']) {
                Evento.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Evento>} eventos
 */
EventoList.prototype['eventos'] = undefined;






export default EventoList;

