/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventoUsuario from './EventoUsuario';

/**
 * The Evento model module.
 * @module model/Evento
 * @version 1.0
 */
class Evento {
    /**
     * Constructs a new <code>Evento</code>.
     * @alias module:model/Evento
     * @param nombre {String} 
     * @param descripcion {String} 
     * @param fecha {Date} 
     */
    constructor(nombre, descripcion, fecha) { 
        
        Evento.initialize(this, nombre, descripcion, fecha);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nombre, descripcion, fecha) { 
        obj['nombre'] = nombre;
        obj['descripcion'] = descripcion;
        obj['fecha'] = fecha;
    }

    /**
     * Constructs a <code>Evento</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Evento} obj Optional instance to populate.
     * @return {module:model/Evento} The populated <code>Evento</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Evento();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('fecha')) {
                obj['fecha'] = ApiClient.convertToType(data['fecha'], 'Date');
            }
            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [EventoUsuario]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Evento</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Evento</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Evento.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }
        // ensure the json data is a string
        if (data['descripcion'] && !(typeof data['descripcion'] === 'string' || data['descripcion'] instanceof String)) {
            throw new Error("Expected the field `descripcion` to be a primitive type in the JSON string but got " + data['descripcion']);
        }
        if (data['users']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['users'])) {
                throw new Error("Expected the field `users` to be an array in the JSON data but got " + data['users']);
            }
            // validate the optional field `users` (array)
            for (const item of data['users']) {
                EventoUsuario.validateJSON(item);
            };
        }

        return true;
    }


}

Evento.RequiredProperties = ["nombre", "descripcion", "fecha"];

/**
 * @member {Number} id
 */
Evento.prototype['id'] = undefined;

/**
 * @member {String} nombre
 */
Evento.prototype['nombre'] = undefined;

/**
 * @member {String} descripcion
 */
Evento.prototype['descripcion'] = undefined;

/**
 * @member {Date} fecha
 */
Evento.prototype['fecha'] = undefined;

/**
 * @member {Array.<module:model/EventoUsuario>} users
 */
Evento.prototype['users'] = undefined;






export default Evento;

