/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Evento model module.
 * @module model/Evento
 * @version 1.0
 */
class Evento {
    /**
     * Constructs a new <code>Evento</code>.
     * @alias module:model/Evento
     * @param descripcion {String} 
     * @param fecha {Date} 
     * @param nombre {String} 
     */
    constructor(descripcion, fecha, nombre) { 
        
        Evento.initialize(this, descripcion, fecha, nombre);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, descripcion, fecha, nombre) { 
        obj['descripcion'] = descripcion;
        obj['fecha'] = fecha;
        obj['nombre'] = nombre;
    }

    /**
     * Constructs a <code>Evento</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Evento} obj Optional instance to populate.
     * @return {module:model/Evento} The populated <code>Evento</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Evento();

            if (data.hasOwnProperty('activo')) {
                obj['activo'] = ApiClient.convertToType(data['activo'], 'Boolean');
            }
            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('fecha')) {
                obj['fecha'] = ApiClient.convertToType(data['fecha'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('idOrganizacion')) {
                obj['idOrganizacion'] = ApiClient.convertToType(data['idOrganizacion'], 'Number');
            }
            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('publicado')) {
                obj['publicado'] = ApiClient.convertToType(data['publicado'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Evento</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Evento</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Evento.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['descripcion'] && !(typeof data['descripcion'] === 'string' || data['descripcion'] instanceof String)) {
            throw new Error("Expected the field `descripcion` to be a primitive type in the JSON string but got " + data['descripcion']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }

        return true;
    }


}

Evento.RequiredProperties = ["descripcion", "fecha", "nombre"];

/**
 * @member {Boolean} activo
 */
Evento.prototype['activo'] = undefined;

/**
 * @member {String} descripcion
 */
Evento.prototype['descripcion'] = undefined;

/**
 * @member {Date} fecha
 */
Evento.prototype['fecha'] = undefined;

/**
 * @member {String} id
 */
Evento.prototype['id'] = undefined;

/**
 * @member {Number} idOrganizacion
 */
Evento.prototype['idOrganizacion'] = undefined;

/**
 * @member {String} nombre
 */
Evento.prototype['nombre'] = undefined;

/**
 * @member {Boolean} publicado
 */
Evento.prototype['publicado'] = undefined;






export default Evento;

