/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventoDonacionesDtoInforme from './EventoDonacionesDtoInforme';

/**
 * The EventoDtoInforme model module.
 * @module model/EventoDtoInforme
 * @version 1.0
 */
class EventoDtoInforme {
    /**
     * Constructs a new <code>EventoDtoInforme</code>.
     * @alias module:model/EventoDtoInforme
     * @param descripcion {String} 
     * @param fecha {Date} 
     * @param nombre {String} 
     */
    constructor(descripcion, fecha, nombre) { 
        
        EventoDtoInforme.initialize(this, descripcion, fecha, nombre);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, descripcion, fecha, nombre) { 
        obj['descripcion'] = descripcion;
        obj['fecha'] = fecha;
        obj['nombre'] = nombre;
    }

    /**
     * Constructs a <code>EventoDtoInforme</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventoDtoInforme} obj Optional instance to populate.
     * @return {module:model/EventoDtoInforme} The populated <code>EventoDtoInforme</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventoDtoInforme();

            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('eventoDonaciones')) {
                obj['eventoDonaciones'] = ApiClient.convertToType(data['eventoDonaciones'], [EventoDonacionesDtoInforme]);
            }
            if (data.hasOwnProperty('fecha')) {
                obj['fecha'] = ApiClient.convertToType(data['fecha'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventoDtoInforme</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventoDtoInforme</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventoDtoInforme.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['descripcion'] && !(typeof data['descripcion'] === 'string' || data['descripcion'] instanceof String)) {
            throw new Error("Expected the field `descripcion` to be a primitive type in the JSON string but got " + data['descripcion']);
        }
        if (data['eventoDonaciones']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['eventoDonaciones'])) {
                throw new Error("Expected the field `eventoDonaciones` to be an array in the JSON data but got " + data['eventoDonaciones']);
            }
            // validate the optional field `eventoDonaciones` (array)
            for (const item of data['eventoDonaciones']) {
                EventoDonacionesDtoInforme.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }

        return true;
    }


}

EventoDtoInforme.RequiredProperties = ["descripcion", "fecha", "nombre"];

/**
 * @member {String} descripcion
 */
EventoDtoInforme.prototype['descripcion'] = undefined;

/**
 * @member {Array.<module:model/EventoDonacionesDtoInforme>} eventoDonaciones
 */
EventoDtoInforme.prototype['eventoDonaciones'] = undefined;

/**
 * @member {Date} fecha
 */
EventoDtoInforme.prototype['fecha'] = undefined;

/**
 * @member {String} id
 */
EventoDtoInforme.prototype['id'] = undefined;

/**
 * @member {String} nombre
 */
EventoDtoInforme.prototype['nombre'] = undefined;






export default EventoDtoInforme;

