/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventoBajaKafka model module.
 * @module model/EventoBajaKafka
 * @version 1.0
 */
class EventoBajaKafka {
    /**
     * Constructs a new <code>EventoBajaKafka</code>.
     * @alias module:model/EventoBajaKafka
     * @param idEvento {String} 
     * @param idOrganizacion {String} 
     */
    constructor(idEvento, idOrganizacion) { 
        
        EventoBajaKafka.initialize(this, idEvento, idOrganizacion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, idEvento, idOrganizacion) { 
        obj['id_evento'] = idEvento;
        obj['id_organizacion'] = idOrganizacion;
    }

    /**
     * Constructs a <code>EventoBajaKafka</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventoBajaKafka} obj Optional instance to populate.
     * @return {module:model/EventoBajaKafka} The populated <code>EventoBajaKafka</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventoBajaKafka();

            if (data.hasOwnProperty('id_evento')) {
                obj['id_evento'] = ApiClient.convertToType(data['id_evento'], 'String');
            }
            if (data.hasOwnProperty('id_organizacion')) {
                obj['id_organizacion'] = ApiClient.convertToType(data['id_organizacion'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventoBajaKafka</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventoBajaKafka</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventoBajaKafka.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id_evento'] && !(typeof data['id_evento'] === 'string' || data['id_evento'] instanceof String)) {
            throw new Error("Expected the field `id_evento` to be a primitive type in the JSON string but got " + data['id_evento']);
        }
        // ensure the json data is a string
        if (data['id_organizacion'] && !(typeof data['id_organizacion'] === 'string' || data['id_organizacion'] instanceof String)) {
            throw new Error("Expected the field `id_organizacion` to be a primitive type in the JSON string but got " + data['id_organizacion']);
        }

        return true;
    }


}

EventoBajaKafka.RequiredProperties = ["id_evento", "id_organizacion"];

/**
 * @member {String} id_evento
 */
EventoBajaKafka.prototype['id_evento'] = undefined;

/**
 * @member {String} id_organizacion
 */
EventoBajaKafka.prototype['id_organizacion'] = undefined;






export default EventoBajaKafka;

