/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventoDonacion from './EventoDonacion';

/**
 * The EventoListaDonacion model module.
 * @module model/EventoListaDonacion
 * @version 1.0
 */
class EventoListaDonacion {
    /**
     * Constructs a new <code>EventoListaDonacion</code>.
     * @alias module:model/EventoListaDonacion
     * @param listaDonacion {Array.<module:model/EventoDonacion>} Lista de las donaciones
     */
    constructor(listaDonacion) { 
        
        EventoListaDonacion.initialize(this, listaDonacion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, listaDonacion) { 
        obj['listaDonacion'] = listaDonacion;
    }

    /**
     * Constructs a <code>EventoListaDonacion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventoListaDonacion} obj Optional instance to populate.
     * @return {module:model/EventoListaDonacion} The populated <code>EventoListaDonacion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventoListaDonacion();

            if (data.hasOwnProperty('idEvento')) {
                obj['idEvento'] = ApiClient.convertToType(data['idEvento'], 'String');
            }
            if (data.hasOwnProperty('listaDonacion')) {
                obj['listaDonacion'] = ApiClient.convertToType(data['listaDonacion'], [EventoDonacion]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventoListaDonacion</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventoListaDonacion</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventoListaDonacion.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['idEvento'] && !(typeof data['idEvento'] === 'string' || data['idEvento'] instanceof String)) {
            throw new Error("Expected the field `idEvento` to be a primitive type in the JSON string but got " + data['idEvento']);
        }
        if (data['listaDonacion']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['listaDonacion'])) {
                throw new Error("Expected the field `listaDonacion` to be an array in the JSON data but got " + data['listaDonacion']);
            }
            // validate the optional field `listaDonacion` (array)
            for (const item of data['listaDonacion']) {
                EventoDonacion.validateJSON(item);
            };
        }

        return true;
    }


}

EventoListaDonacion.RequiredProperties = ["listaDonacion"];

/**
 * @member {String} idEvento
 */
EventoListaDonacion.prototype['idEvento'] = undefined;

/**
 * Lista de las donaciones
 * @member {Array.<module:model/EventoDonacion>} listaDonacion
 */
EventoListaDonacion.prototype['listaDonacion'] = undefined;






export default EventoListaDonacion;

