/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventoDonacionObjeto from './EventoDonacionObjeto';

/**
 * The EventoDonacionesDtoInforme model module.
 * @module model/EventoDonacionesDtoInforme
 * @version 1.0
 */
class EventoDonacionesDtoInforme {
    /**
     * Constructs a new <code>EventoDonacionesDtoInforme</code>.
     * @alias module:model/EventoDonacionesDtoInforme
     * @param cantRepartida {Number} 
     * @param donacion {module:model/EventoDonacionObjeto} 
     */
    constructor(cantRepartida, donacion) { 
        
        EventoDonacionesDtoInforme.initialize(this, cantRepartida, donacion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cantRepartida, donacion) { 
        obj['cantRepartida'] = cantRepartida;
        obj['donacion'] = donacion;
    }

    /**
     * Constructs a <code>EventoDonacionesDtoInforme</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EventoDonacionesDtoInforme} obj Optional instance to populate.
     * @return {module:model/EventoDonacionesDtoInforme} The populated <code>EventoDonacionesDtoInforme</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EventoDonacionesDtoInforme();

            if (data.hasOwnProperty('cantRepartida')) {
                obj['cantRepartida'] = ApiClient.convertToType(data['cantRepartida'], 'Number');
            }
            if (data.hasOwnProperty('donacion')) {
                obj['donacion'] = EventoDonacionObjeto.constructFromObject(data['donacion']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EventoDonacionesDtoInforme</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EventoDonacionesDtoInforme</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EventoDonacionesDtoInforme.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `donacion`
        if (data['donacion']) { // data not null
          EventoDonacionObjeto.validateJSON(data['donacion']);
        }

        return true;
    }


}

EventoDonacionesDtoInforme.RequiredProperties = ["cantRepartida", "donacion"];

/**
 * @member {Number} cantRepartida
 */
EventoDonacionesDtoInforme.prototype['cantRepartida'] = undefined;

/**
 * @member {module:model/EventoDonacionObjeto} donacion
 */
EventoDonacionesDtoInforme.prototype['donacion'] = undefined;






export default EventoDonacionesDtoInforme;

