/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FiltroEvento model module.
 * @module model/FiltroEvento
 * @version 1.0
 */
class FiltroEvento {
    /**
     * Constructs a new <code>FiltroEvento</code>.
     * @alias module:model/FiltroEvento
     * @param usuarioId {String} 
     * @param tieneDonacion {Number} 
     */
    constructor(usuarioId, tieneDonacion) { 
        
        FiltroEvento.initialize(this, usuarioId, tieneDonacion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, usuarioId, tieneDonacion) { 
        obj['usuarioId'] = usuarioId;
        obj['tieneDonacion'] = tieneDonacion;
    }

    /**
     * Constructs a <code>FiltroEvento</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FiltroEvento} obj Optional instance to populate.
     * @return {module:model/FiltroEvento} The populated <code>FiltroEvento</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FiltroEvento();

            if (data.hasOwnProperty('usuarioId')) {
                obj['usuarioId'] = ApiClient.convertToType(data['usuarioId'], 'String');
            }
            if (data.hasOwnProperty('fechaDesde')) {
                obj['fechaDesde'] = ApiClient.convertToType(data['fechaDesde'], 'Date');
            }
            if (data.hasOwnProperty('fechaHasta')) {
                obj['fechaHasta'] = ApiClient.convertToType(data['fechaHasta'], 'Date');
            }
            if (data.hasOwnProperty('tieneDonacion')) {
                obj['tieneDonacion'] = ApiClient.convertToType(data['tieneDonacion'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FiltroEvento</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FiltroEvento</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FiltroEvento.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['usuarioId'] && !(typeof data['usuarioId'] === 'string' || data['usuarioId'] instanceof String)) {
            throw new Error("Expected the field `usuarioId` to be a primitive type in the JSON string but got " + data['usuarioId']);
        }

        return true;
    }


}

FiltroEvento.RequiredProperties = ["usuarioId", "tieneDonacion"];

/**
 * @member {String} usuarioId
 */
FiltroEvento.prototype['usuarioId'] = undefined;

/**
 * @member {Date} fechaDesde
 */
FiltroEvento.prototype['fechaDesde'] = undefined;

/**
 * @member {Date} fechaHasta
 */
FiltroEvento.prototype['fechaHasta'] = undefined;

/**
 * @member {Number} tieneDonacion
 */
FiltroEvento.prototype['tieneDonacion'] = undefined;






export default FiltroEvento;

