/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InformeParticipacionEventos from './InformeParticipacionEventos';

/**
 * The InformeEventosDto model module.
 * @module model/InformeEventosDto
 * @version 1.0
 */
class InformeEventosDto {
    /**
     * Constructs a new <code>InformeEventosDto</code>.
     * @alias module:model/InformeEventosDto
     */
    constructor() { 
        
        InformeEventosDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InformeEventosDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InformeEventosDto} obj Optional instance to populate.
     * @return {module:model/InformeEventosDto} The populated <code>InformeEventosDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InformeEventosDto();

            if (data.hasOwnProperty('informeParticipacionEventos')) {
                obj['informeParticipacionEventos'] = ApiClient.convertToType(data['informeParticipacionEventos'], [InformeParticipacionEventos]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InformeEventosDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InformeEventosDto</code>.
     */
    static validateJSON(data) {
        if (data['informeParticipacionEventos']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['informeParticipacionEventos'])) {
                throw new Error("Expected the field `informeParticipacionEventos` to be an array in the JSON data but got " + data['informeParticipacionEventos']);
            }
            // validate the optional field `informeParticipacionEventos` (array)
            for (const item of data['informeParticipacionEventos']) {
                InformeParticipacionEventos.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/InformeParticipacionEventos>} informeParticipacionEventos
 */
InformeEventosDto.prototype['informeParticipacionEventos'] = undefined;






export default InformeEventosDto;

