/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InformeSolicitud from './InformeSolicitud';

/**
 * The InformeSolicitudList model module.
 * @module model/InformeSolicitudList
 * @version 1.0
 */
class InformeSolicitudList {
    /**
     * Constructs a new <code>InformeSolicitudList</code>.
     * @alias module:model/InformeSolicitudList
     * @param message {String} 
     * @param status {String} 
     */
    constructor(message, status) { 
        
        InformeSolicitudList.initialize(this, message, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, status) { 
        obj['message'] = message;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>InformeSolicitudList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InformeSolicitudList} obj Optional instance to populate.
     * @return {module:model/InformeSolicitudList} The populated <code>InformeSolicitudList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InformeSolicitudList();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [InformeSolicitud]);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InformeSolicitudList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InformeSolicitudList</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InformeSolicitudList.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                InformeSolicitud.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

InformeSolicitudList.RequiredProperties = ["message", "status"];

/**
 * @member {Array.<module:model/InformeSolicitud>} data
 */
InformeSolicitudList.prototype['data'] = undefined;

/**
 * @member {String} message
 */
InformeSolicitudList.prototype['message'] = undefined;

/**
 * @member {String} status
 */
InformeSolicitudList.prototype['status'] = undefined;






export default InformeSolicitudList;

