/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OfertaGet from './OfertaGet';

/**
 * The OfertaGetList model module.
 * @module model/OfertaGetList
 * @version 1.0
 */
class OfertaGetList {
    /**
     * Constructs a new <code>OfertaGetList</code>.
     * @alias module:model/OfertaGetList
     */
    constructor() { 
        
        OfertaGetList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OfertaGetList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OfertaGetList} obj Optional instance to populate.
     * @return {module:model/OfertaGetList} The populated <code>OfertaGetList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OfertaGetList();

            if (data.hasOwnProperty('ofertas')) {
                obj['ofertas'] = ApiClient.convertToType(data['ofertas'], [OfertaGet]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OfertaGetList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OfertaGetList</code>.
     */
    static validateJSON(data) {
        if (data['ofertas']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ofertas'])) {
                throw new Error("Expected the field `ofertas` to be an array in the JSON data but got " + data['ofertas']);
            }
            // validate the optional field `ofertas` (array)
            for (const item of data['ofertas']) {
                OfertaGet.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/OfertaGet>} ofertas
 */
OfertaGetList.prototype['ofertas'] = undefined;






export default OfertaGetList;

