/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SolicitudDonacion from './SolicitudDonacion';

/**
 * The Oferta model module.
 * @module model/Oferta
 * @version 1.0
 */
class Oferta {
    /**
     * Constructs a new <code>Oferta</code>.
     * @alias module:model/Oferta
     * @param idOferta {Number} 
     * @param idOrganizacionDonante {Number} 
     */
    constructor(idOferta, idOrganizacionDonante) { 
        
        Oferta.initialize(this, idOferta, idOrganizacionDonante);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, idOferta, idOrganizacionDonante) { 
        obj['id_oferta'] = idOferta;
        obj['id_organizacion_donante'] = idOrganizacionDonante;
    }

    /**
     * Constructs a <code>Oferta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Oferta} obj Optional instance to populate.
     * @return {module:model/Oferta} The populated <code>Oferta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Oferta();

            if (data.hasOwnProperty('donaciones')) {
                obj['donaciones'] = ApiClient.convertToType(data['donaciones'], [SolicitudDonacion]);
            }
            if (data.hasOwnProperty('id_oferta')) {
                obj['id_oferta'] = ApiClient.convertToType(data['id_oferta'], 'Number');
            }
            if (data.hasOwnProperty('id_organizacion_donante')) {
                obj['id_organizacion_donante'] = ApiClient.convertToType(data['id_organizacion_donante'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Oferta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Oferta</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Oferta.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['donaciones']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['donaciones'])) {
                throw new Error("Expected the field `donaciones` to be an array in the JSON data but got " + data['donaciones']);
            }
            // validate the optional field `donaciones` (array)
            for (const item of data['donaciones']) {
                SolicitudDonacion.validateJSON(item);
            };
        }

        return true;
    }


}

Oferta.RequiredProperties = ["id_oferta", "id_organizacion_donante"];

/**
 * @member {Array.<module:model/SolicitudDonacion>} donaciones
 */
Oferta.prototype['donaciones'] = undefined;

/**
 * @member {Number} id_oferta
 */
Oferta.prototype['id_oferta'] = undefined;

/**
 * @member {Number} id_organizacion_donante
 */
Oferta.prototype['id_organizacion_donante'] = undefined;






export default Oferta;

