/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SolicitudDonacion from './SolicitudDonacion';
import SolicitudOrganizacionDto from './SolicitudOrganizacionDto';

/**
 * The OfertaGet model module.
 * @module model/OfertaGet
 * @version 1.0
 */
class OfertaGet {
    /**
     * Constructs a new <code>OfertaGet</code>.
     * @alias module:model/OfertaGet
     * @param id {String} 
     */
    constructor(id) { 
        
        OfertaGet.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>OfertaGet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OfertaGet} obj Optional instance to populate.
     * @return {module:model/OfertaGet} The populated <code>OfertaGet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OfertaGet();

            if (data.hasOwnProperty('donaciones')) {
                obj['donaciones'] = ApiClient.convertToType(data['donaciones'], [SolicitudDonacion]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('organizacionDonante')) {
                obj['organizacionDonante'] = SolicitudOrganizacionDto.constructFromObject(data['organizacionDonante']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OfertaGet</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OfertaGet</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OfertaGet.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['donaciones']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['donaciones'])) {
                throw new Error("Expected the field `donaciones` to be an array in the JSON data but got " + data['donaciones']);
            }
            // validate the optional field `donaciones` (array)
            for (const item of data['donaciones']) {
                SolicitudDonacion.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `organizacionDonante`
        if (data['organizacionDonante']) { // data not null
          SolicitudOrganizacionDto.validateJSON(data['organizacionDonante']);
        }

        return true;
    }


}

OfertaGet.RequiredProperties = ["id"];

/**
 * @member {Array.<module:model/SolicitudDonacion>} donaciones
 */
OfertaGet.prototype['donaciones'] = undefined;

/**
 * @member {String} id
 */
OfertaGet.prototype['id'] = undefined;

/**
 * @member {module:model/SolicitudOrganizacionDto} organizacionDonante
 */
OfertaGet.prototype['organizacionDonante'] = undefined;






export default OfertaGet;

