/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SolicitudGet from './SolicitudGet';

/**
 * The SolicitudGetList model module.
 * @module model/SolicitudGetList
 * @version 1.0
 */
class SolicitudGetList {
    /**
     * Constructs a new <code>SolicitudGetList</code>.
     * @alias module:model/SolicitudGetList
     */
    constructor() { 
        
        SolicitudGetList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SolicitudGetList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SolicitudGetList} obj Optional instance to populate.
     * @return {module:model/SolicitudGetList} The populated <code>SolicitudGetList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SolicitudGetList();

            if (data.hasOwnProperty('solicitudes')) {
                obj['solicitudes'] = ApiClient.convertToType(data['solicitudes'], [SolicitudGet]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SolicitudGetList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SolicitudGetList</code>.
     */
    static validateJSON(data) {
        if (data['solicitudes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['solicitudes'])) {
                throw new Error("Expected the field `solicitudes` to be an array in the JSON data but got " + data['solicitudes']);
            }
            // validate the optional field `solicitudes` (array)
            for (const item of data['solicitudes']) {
                SolicitudGet.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/SolicitudGet>} solicitudes
 */
SolicitudGetList.prototype['solicitudes'] = undefined;






export default SolicitudGetList;

