/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SolicitudVariablesInformeSolicitud model module.
 * @module model/SolicitudVariablesInformeSolicitud
 * @version 1.0
 */
class SolicitudVariablesInformeSolicitud {
    /**
     * Constructs a new <code>SolicitudVariablesInformeSolicitud</code>.
     * @alias module:model/SolicitudVariablesInformeSolicitud
     */
    constructor() { 
        
        SolicitudVariablesInformeSolicitud.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SolicitudVariablesInformeSolicitud</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SolicitudVariablesInformeSolicitud} obj Optional instance to populate.
     * @return {module:model/SolicitudVariablesInformeSolicitud} The populated <code>SolicitudVariablesInformeSolicitud</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SolicitudVariablesInformeSolicitud();

            if (data.hasOwnProperty('categoria')) {
                obj['categoria'] = ApiClient.convertToType(data['categoria'], 'String');
            }
            if (data.hasOwnProperty('fechaDesde')) {
                obj['fechaDesde'] = ApiClient.convertToType(data['fechaDesde'], 'String');
            }
            if (data.hasOwnProperty('fechaHasta')) {
                obj['fechaHasta'] = ApiClient.convertToType(data['fechaHasta'], 'String');
            }
            if (data.hasOwnProperty('eliminado')) {
                obj['eliminado'] = ApiClient.convertToType(data['eliminado'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SolicitudVariablesInformeSolicitud</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SolicitudVariablesInformeSolicitud</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['categoria'] && !(typeof data['categoria'] === 'string' || data['categoria'] instanceof String)) {
            throw new Error("Expected the field `categoria` to be a primitive type in the JSON string but got " + data['categoria']);
        }
        // ensure the json data is a string
        if (data['fechaDesde'] && !(typeof data['fechaDesde'] === 'string' || data['fechaDesde'] instanceof String)) {
            throw new Error("Expected the field `fechaDesde` to be a primitive type in the JSON string but got " + data['fechaDesde']);
        }
        // ensure the json data is a string
        if (data['fechaHasta'] && !(typeof data['fechaHasta'] === 'string' || data['fechaHasta'] instanceof String)) {
            throw new Error("Expected the field `fechaHasta` to be a primitive type in the JSON string but got " + data['fechaHasta']);
        }
        // ensure the json data is a string
        if (data['eliminado'] && !(typeof data['eliminado'] === 'string' || data['eliminado'] instanceof String)) {
            throw new Error("Expected the field `eliminado` to be a primitive type in the JSON string but got " + data['eliminado']);
        }

        return true;
    }


}



/**
 * @member {String} categoria
 */
SolicitudVariablesInformeSolicitud.prototype['categoria'] = undefined;

/**
 * @member {String} fechaDesde
 */
SolicitudVariablesInformeSolicitud.prototype['fechaDesde'] = undefined;

/**
 * @member {String} fechaHasta
 */
SolicitudVariablesInformeSolicitud.prototype['fechaHasta'] = undefined;

/**
 * @member {String} eliminado
 */
SolicitudVariablesInformeSolicitud.prototype['eliminado'] = undefined;






export default SolicitudVariablesInformeSolicitud;

