/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SolicitudGraphQLInformeEnvelope from './SolicitudGraphQLInformeEnvelope';

/**
 * The SolicitudGraphQLResponse model module.
 * @module model/SolicitudGraphQLResponse
 * @version 1.0
 */
class SolicitudGraphQLResponse {
    /**
     * Constructs a new <code>SolicitudGraphQLResponse</code>.
     * @alias module:model/SolicitudGraphQLResponse
     */
    constructor() { 
        
        SolicitudGraphQLResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SolicitudGraphQLResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SolicitudGraphQLResponse} obj Optional instance to populate.
     * @return {module:model/SolicitudGraphQLResponse} The populated <code>SolicitudGraphQLResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SolicitudGraphQLResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = SolicitudGraphQLInformeEnvelope.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SolicitudGraphQLResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SolicitudGraphQLResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          SolicitudGraphQLInformeEnvelope.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/SolicitudGraphQLInformeEnvelope} data
 */
SolicitudGraphQLResponse.prototype['data'] = undefined;






export default SolicitudGraphQLResponse;

