/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SolicitudDonacion from './SolicitudDonacion';

/**
 * The SolicitudTransferDonation model module.
 * @module model/SolicitudTransferDonation
 * @version 1.0
 */
class SolicitudTransferDonation {
    /**
     * Constructs a new <code>SolicitudTransferDonation</code>.
     * @alias module:model/SolicitudTransferDonation
     * @param idOrganizacionDonante {Number} 
     * @param idSolicitud {String} 
     */
    constructor(idOrganizacionDonante, idSolicitud) { 
        
        SolicitudTransferDonation.initialize(this, idOrganizacionDonante, idSolicitud);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, idOrganizacionDonante, idSolicitud) { 
        obj['id_organizacion_donante'] = idOrganizacionDonante;
        obj['id_solicitud'] = idSolicitud;
    }

    /**
     * Constructs a <code>SolicitudTransferDonation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SolicitudTransferDonation} obj Optional instance to populate.
     * @return {module:model/SolicitudTransferDonation} The populated <code>SolicitudTransferDonation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SolicitudTransferDonation();

            if (data.hasOwnProperty('donaciones')) {
                obj['donaciones'] = ApiClient.convertToType(data['donaciones'], [SolicitudDonacion]);
            }
            if (data.hasOwnProperty('id_organizacion_donante')) {
                obj['id_organizacion_donante'] = ApiClient.convertToType(data['id_organizacion_donante'], 'Number');
            }
            if (data.hasOwnProperty('id_solicitud')) {
                obj['id_solicitud'] = ApiClient.convertToType(data['id_solicitud'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SolicitudTransferDonation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SolicitudTransferDonation</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SolicitudTransferDonation.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['donaciones']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['donaciones'])) {
                throw new Error("Expected the field `donaciones` to be an array in the JSON data but got " + data['donaciones']);
            }
            // validate the optional field `donaciones` (array)
            for (const item of data['donaciones']) {
                SolicitudDonacion.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['id_solicitud'] && !(typeof data['id_solicitud'] === 'string' || data['id_solicitud'] instanceof String)) {
            throw new Error("Expected the field `id_solicitud` to be a primitive type in the JSON string but got " + data['id_solicitud']);
        }

        return true;
    }


}

SolicitudTransferDonation.RequiredProperties = ["id_organizacion_donante", "id_solicitud"];

/**
 * @member {Array.<module:model/SolicitudDonacion>} donaciones
 */
SolicitudTransferDonation.prototype['donaciones'] = undefined;

/**
 * @member {Number} id_organizacion_donante
 */
SolicitudTransferDonation.prototype['id_organizacion_donante'] = undefined;

/**
 * @member {String} id_solicitud
 */
SolicitudTransferDonation.prototype['id_solicitud'] = undefined;






export default SolicitudTransferDonation;

