/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SolicitudOrganizacionDto model module.
 * @module model/SolicitudOrganizacionDto
 * @version 1.0
 */
class SolicitudOrganizacionDto {
    /**
     * Constructs a new <code>SolicitudOrganizacionDto</code>.
     * @alias module:model/SolicitudOrganizacionDto
     * @param id {Number} 
     * @param nombre {String} 
     */
    constructor(id, nombre) { 
        
        SolicitudOrganizacionDto.initialize(this, id, nombre);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, nombre) { 
        obj['id'] = id;
        obj['nombre'] = nombre;
    }

    /**
     * Constructs a <code>SolicitudOrganizacionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SolicitudOrganizacionDto} obj Optional instance to populate.
     * @return {module:model/SolicitudOrganizacionDto} The populated <code>SolicitudOrganizacionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SolicitudOrganizacionDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('externa')) {
                obj['externa'] = ApiClient.convertToType(data['externa'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SolicitudOrganizacionDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SolicitudOrganizacionDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SolicitudOrganizacionDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }

        return true;
    }


}

SolicitudOrganizacionDto.RequiredProperties = ["id", "nombre"];

/**
 * @member {Number} id
 */
SolicitudOrganizacionDto.prototype['id'] = undefined;

/**
 * @member {String} nombre
 */
SolicitudOrganizacionDto.prototype['nombre'] = undefined;

/**
 * @member {Boolean} externa
 */
SolicitudOrganizacionDto.prototype['externa'] = undefined;






export default SolicitudOrganizacionDto;

