/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Solicitud from './Solicitud';

/**
 * The SolicitudList model module.
 * @module model/SolicitudList
 * @version 1.0
 */
class SolicitudList {
    /**
     * Constructs a new <code>SolicitudList</code>.
     * @alias module:model/SolicitudList
     */
    constructor() { 
        
        SolicitudList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SolicitudList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SolicitudList} obj Optional instance to populate.
     * @return {module:model/SolicitudList} The populated <code>SolicitudList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SolicitudList();

            if (data.hasOwnProperty('solicitudes')) {
                obj['solicitudes'] = ApiClient.convertToType(data['solicitudes'], [Solicitud]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SolicitudList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SolicitudList</code>.
     */
    static validateJSON(data) {
        if (data['solicitudes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['solicitudes'])) {
                throw new Error("Expected the field `solicitudes` to be an array in the JSON data but got " + data['solicitudes']);
            }
            // validate the optional field `solicitudes` (array)
            for (const item of data['solicitudes']) {
                Solicitud.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Solicitud>} solicitudes
 */
SolicitudList.prototype['solicitudes'] = undefined;






export default SolicitudList;

