/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SolicitudDonacion from './SolicitudDonacion';

/**
 * The Solicitud model module.
 * @module model/Solicitud
 * @version 1.0
 */
class Solicitud {
    /**
     * Constructs a new <code>Solicitud</code>.
     * @alias module:model/Solicitud
     * @param idSolicitudDonacion {Number} 
     * @param idOrganizacionSolicitante {Number} 
     */
    constructor(idSolicitudDonacion, idOrganizacionSolicitante) { 
        
        Solicitud.initialize(this, idSolicitudDonacion, idOrganizacionSolicitante);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, idSolicitudDonacion, idOrganizacionSolicitante) { 
        obj['id_solicitud_donacion'] = idSolicitudDonacion;
        obj['id_organizacion_solicitante'] = idOrganizacionSolicitante;
    }

    /**
     * Constructs a <code>Solicitud</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Solicitud} obj Optional instance to populate.
     * @return {module:model/Solicitud} The populated <code>Solicitud</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Solicitud();

            if (data.hasOwnProperty('id_solicitud_donacion')) {
                obj['id_solicitud_donacion'] = ApiClient.convertToType(data['id_solicitud_donacion'], 'Number');
            }
            if (data.hasOwnProperty('id_organizacion_solicitante')) {
                obj['id_organizacion_solicitante'] = ApiClient.convertToType(data['id_organizacion_solicitante'], 'Number');
            }
            if (data.hasOwnProperty('donacion')) {
                obj['donacion'] = ApiClient.convertToType(data['donacion'], [SolicitudDonacion]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Solicitud</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Solicitud</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Solicitud.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['donacion']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['donacion'])) {
                throw new Error("Expected the field `donacion` to be an array in the JSON data but got " + data['donacion']);
            }
            // validate the optional field `donacion` (array)
            for (const item of data['donacion']) {
                SolicitudDonacion.validateJSON(item);
            };
        }

        return true;
    }


}

Solicitud.RequiredProperties = ["id_solicitud_donacion", "id_organizacion_solicitante"];

/**
 * @member {Number} id_solicitud_donacion
 */
Solicitud.prototype['id_solicitud_donacion'] = undefined;

/**
 * @member {Number} id_organizacion_solicitante
 */
Solicitud.prototype['id_organizacion_solicitante'] = undefined;

/**
 * @member {Array.<module:model/SolicitudDonacion>} donacion
 */
Solicitud.prototype['donacion'] = undefined;






export default Solicitud;

