/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InformeSolicitudList from './InformeSolicitudList';

/**
 * The SolicitudGraphQLInformeEnvelope model module.
 * @module model/SolicitudGraphQLInformeEnvelope
 * @version 1.0
 */
class SolicitudGraphQLInformeEnvelope {
    /**
     * Constructs a new <code>SolicitudGraphQLInformeEnvelope</code>.
     * @alias module:model/SolicitudGraphQLInformeEnvelope
     */
    constructor() { 
        
        SolicitudGraphQLInformeEnvelope.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SolicitudGraphQLInformeEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SolicitudGraphQLInformeEnvelope} obj Optional instance to populate.
     * @return {module:model/SolicitudGraphQLInformeEnvelope} The populated <code>SolicitudGraphQLInformeEnvelope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SolicitudGraphQLInformeEnvelope();

            if (data.hasOwnProperty('informeSolicitudes')) {
                obj['informeSolicitudes'] = InformeSolicitudList.constructFromObject(data['informeSolicitudes']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SolicitudGraphQLInformeEnvelope</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SolicitudGraphQLInformeEnvelope</code>.
     */
    static validateJSON(data) {
        // validate the optional field `informeSolicitudes`
        if (data['informeSolicitudes']) { // data not null
          InformeSolicitudList.validateJSON(data['informeSolicitudes']);
        }

        return true;
    }


}



/**
 * @member {module:model/InformeSolicitudList} informeSolicitudes
 */
SolicitudGraphQLInformeEnvelope.prototype['informeSolicitudes'] = undefined;






export default SolicitudGraphQLInformeEnvelope;

