/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SolicitudCategoria from './SolicitudCategoria';

/**
 * The SolicitudDonacion model module.
 * @module model/SolicitudDonacion
 * @version 1.0
 */
class SolicitudDonacion {
    /**
     * Constructs a new <code>SolicitudDonacion</code>.
     * @alias module:model/SolicitudDonacion
     * @param categoria {module:model/SolicitudCategoria} 
     * @param descripcion {String} 
     * @param cantidad {Number} 
     */
    constructor(categoria, descripcion, cantidad) { 
        
        SolicitudDonacion.initialize(this, categoria, descripcion, cantidad);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, categoria, descripcion, cantidad) { 
        obj['categoria'] = categoria;
        obj['descripcion'] = descripcion;
        obj['cantidad'] = cantidad;
    }

    /**
     * Constructs a <code>SolicitudDonacion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SolicitudDonacion} obj Optional instance to populate.
     * @return {module:model/SolicitudDonacion} The populated <code>SolicitudDonacion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SolicitudDonacion();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('categoria')) {
                obj['categoria'] = SolicitudCategoria.constructFromObject(data['categoria']);
            }
            if (data.hasOwnProperty('descripcion')) {
                obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
            }
            if (data.hasOwnProperty('cantidad')) {
                obj['cantidad'] = ApiClient.convertToType(data['cantidad'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SolicitudDonacion</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SolicitudDonacion</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SolicitudDonacion.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `categoria`
        if (data['categoria']) { // data not null
          SolicitudCategoria.validateJSON(data['categoria']);
        }
        // ensure the json data is a string
        if (data['descripcion'] && !(typeof data['descripcion'] === 'string' || data['descripcion'] instanceof String)) {
            throw new Error("Expected the field `descripcion` to be a primitive type in the JSON string but got " + data['descripcion']);
        }

        return true;
    }


}

SolicitudDonacion.RequiredProperties = ["categoria", "descripcion", "cantidad"];

/**
 * @member {Number} id
 */
SolicitudDonacion.prototype['id'] = undefined;

/**
 * @member {module:model/SolicitudCategoria} categoria
 */
SolicitudDonacion.prototype['categoria'] = undefined;

/**
 * @member {String} descripcion
 */
SolicitudDonacion.prototype['descripcion'] = undefined;

/**
 * @member {Number} cantidad
 */
SolicitudDonacion.prototype['cantidad'] = undefined;






export default SolicitudDonacion;

