/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubirFilGraphql from './SubirFilGraphql';

/**
 * The SubirVarGraphql model module.
 * @module model/SubirVarGraphql
 * @version 1.0
 */
class SubirVarGraphql {
    /**
     * Constructs a new <code>SubirVarGraphql</code>.
     * @alias module:model/SubirVarGraphql
     */
    constructor() { 
        
        SubirVarGraphql.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubirVarGraphql</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubirVarGraphql} obj Optional instance to populate.
     * @return {module:model/SubirVarGraphql} The populated <code>SubirVarGraphql</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubirVarGraphql();

            if (data.hasOwnProperty('filtro')) {
                obj['filtro'] = SubirFilGraphql.constructFromObject(data['filtro']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubirVarGraphql</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubirVarGraphql</code>.
     */
    static validateJSON(data) {
        // validate the optional field `filtro`
        if (data['filtro']) { // data not null
          SubirFilGraphql.validateJSON(data['filtro']);
        }

        return true;
    }


}



/**
 * @member {module:model/SubirFilGraphql} filtro
 */
SubirVarGraphql.prototype['filtro'] = undefined;






export default SubirVarGraphql;

