/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubirVarGraphql from './SubirVarGraphql';

/**
 * The SubirQueryGraphql model module.
 * @module model/SubirQueryGraphql
 * @version 1.0
 */
class SubirQueryGraphql {
    /**
     * Constructs a new <code>SubirQueryGraphql</code>.
     * @alias module:model/SubirQueryGraphql
     * @param query {String} 
     */
    constructor(query) { 
        
        SubirQueryGraphql.initialize(this, query);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, query) { 
        obj['query'] = query || 'mutation GuardarFiltro($filtro: FilterInput!) { guardarFiltro(filtro: $filtro) { status message data { id name valueFilter usuario filterType } } }';
    }

    /**
     * Constructs a <code>SubirQueryGraphql</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubirQueryGraphql} obj Optional instance to populate.
     * @return {module:model/SubirQueryGraphql} The populated <code>SubirQueryGraphql</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubirQueryGraphql();

            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = SubirVarGraphql.constructFromObject(data['variables']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubirQueryGraphql</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubirQueryGraphql</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubirQueryGraphql.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['query'] && !(typeof data['query'] === 'string' || data['query'] instanceof String)) {
            throw new Error("Expected the field `query` to be a primitive type in the JSON string but got " + data['query']);
        }
        // validate the optional field `variables`
        if (data['variables']) { // data not null
          SubirVarGraphql.validateJSON(data['variables']);
        }

        return true;
    }


}

SubirQueryGraphql.RequiredProperties = ["query"];

/**
 * @member {String} query
 * @default 'mutation GuardarFiltro($filtro: FilterInput!) { guardarFiltro(filtro: $filtro) { status message data { id name valueFilter usuario filterType } } }'
 */
SubirQueryGraphql.prototype['query'] = 'mutation GuardarFiltro($filtro: FilterInput!) { guardarFiltro(filtro: $filtro) { status message data { id name valueFilter usuario filterType } } }';

/**
 * @member {module:model/SubirVarGraphql} variables
 */
SubirQueryGraphql.prototype['variables'] = undefined;






export default SubirQueryGraphql;

