/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResDataGraphql from './ResDataGraphql';

/**
 * The TraerFiltrosGraphqlDto model module.
 * @module model/TraerFiltrosGraphqlDto
 * @version 1.0
 */
class TraerFiltrosGraphqlDto {
    /**
     * Constructs a new <code>TraerFiltrosGraphqlDto</code>.
     * @alias module:model/TraerFiltrosGraphqlDto
     * @param status {String} 
     * @param message {String} 
     */
    constructor(status, message) { 
        
        TraerFiltrosGraphqlDto.initialize(this, status, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, message) { 
        obj['status'] = status;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>TraerFiltrosGraphqlDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TraerFiltrosGraphqlDto} obj Optional instance to populate.
     * @return {module:model/TraerFiltrosGraphqlDto} The populated <code>TraerFiltrosGraphqlDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TraerFiltrosGraphqlDto();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [ResDataGraphql]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TraerFiltrosGraphqlDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TraerFiltrosGraphqlDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TraerFiltrosGraphqlDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                ResDataGraphql.validateJSON(item);
            };
        }

        return true;
    }


}

TraerFiltrosGraphqlDto.RequiredProperties = ["status", "message"];

/**
 * @member {String} status
 */
TraerFiltrosGraphqlDto.prototype['status'] = undefined;

/**
 * @member {String} message
 */
TraerFiltrosGraphqlDto.prototype['message'] = undefined;

/**
 * @member {Array.<module:model/ResDataGraphql>} data
 */
TraerFiltrosGraphqlDto.prototype['data'] = undefined;






export default TraerFiltrosGraphqlDto;

