/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TraerFiltrosGraphqlDto from './TraerFiltrosGraphqlDto';

/**
 * The TraerFiltrosGraphQLEnvelope model module.
 * @module model/TraerFiltrosGraphQLEnvelope
 * @version 1.0
 */
class TraerFiltrosGraphQLEnvelope {
    /**
     * Constructs a new <code>TraerFiltrosGraphQLEnvelope</code>.
     * @alias module:model/TraerFiltrosGraphQLEnvelope
     */
    constructor() { 
        
        TraerFiltrosGraphQLEnvelope.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TraerFiltrosGraphQLEnvelope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TraerFiltrosGraphQLEnvelope} obj Optional instance to populate.
     * @return {module:model/TraerFiltrosGraphQLEnvelope} The populated <code>TraerFiltrosGraphQLEnvelope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TraerFiltrosGraphQLEnvelope();

            if (data.hasOwnProperty('traerFiltros')) {
                obj['traerFiltros'] = TraerFiltrosGraphqlDto.constructFromObject(data['traerFiltros']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TraerFiltrosGraphQLEnvelope</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TraerFiltrosGraphQLEnvelope</code>.
     */
    static validateJSON(data) {
        // validate the optional field `traerFiltros`
        if (data['traerFiltros']) { // data not null
          TraerFiltrosGraphqlDto.validateJSON(data['traerFiltros']);
        }

        return true;
    }


}



/**
 * @member {module:model/TraerFiltrosGraphqlDto} traerFiltros
 */
TraerFiltrosGraphQLEnvelope.prototype['traerFiltros'] = undefined;






export default TraerFiltrosGraphQLEnvelope;

