/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TraerVarGraphqlDto model module.
 * @module model/TraerVarGraphqlDto
 * @version 1.0
 */
class TraerVarGraphqlDto {
    /**
     * Constructs a new <code>TraerVarGraphqlDto</code>.
     * @alias module:model/TraerVarGraphqlDto
     * @param usuario {String} 
     * @param tipo {String} 
     */
    constructor(usuario, tipo) { 
        
        TraerVarGraphqlDto.initialize(this, usuario, tipo);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, usuario, tipo) { 
        obj['usuario'] = usuario;
        obj['tipo'] = tipo;
    }

    /**
     * Constructs a <code>TraerVarGraphqlDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TraerVarGraphqlDto} obj Optional instance to populate.
     * @return {module:model/TraerVarGraphqlDto} The populated <code>TraerVarGraphqlDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TraerVarGraphqlDto();

            if (data.hasOwnProperty('usuario')) {
                obj['usuario'] = ApiClient.convertToType(data['usuario'], 'String');
            }
            if (data.hasOwnProperty('tipo')) {
                obj['tipo'] = ApiClient.convertToType(data['tipo'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TraerVarGraphqlDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TraerVarGraphqlDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TraerVarGraphqlDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['usuario'] && !(typeof data['usuario'] === 'string' || data['usuario'] instanceof String)) {
            throw new Error("Expected the field `usuario` to be a primitive type in the JSON string but got " + data['usuario']);
        }
        // ensure the json data is a string
        if (data['tipo'] && !(typeof data['tipo'] === 'string' || data['tipo'] instanceof String)) {
            throw new Error("Expected the field `tipo` to be a primitive type in the JSON string but got " + data['tipo']);
        }

        return true;
    }


}

TraerVarGraphqlDto.RequiredProperties = ["usuario", "tipo"];

/**
 * @member {String} usuario
 */
TraerVarGraphqlDto.prototype['usuario'] = undefined;

/**
 * @member {String} tipo
 */
TraerVarGraphqlDto.prototype['tipo'] = undefined;






export default TraerVarGraphqlDto;

