/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsersListDto model module.
 * @module model/UsersListDto
 * @version 1.0
 */
class UsersListDto {
    /**
     * Constructs a new <code>UsersListDto</code>.
     * @alias module:model/UsersListDto
     * @param usersIds {Array.<Number>} Lista de IDs de usuarios
     */
    constructor(usersIds) { 
        
        UsersListDto.initialize(this, usersIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, usersIds) { 
        obj['usersIds'] = usersIds;
    }

    /**
     * Constructs a <code>UsersListDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsersListDto} obj Optional instance to populate.
     * @return {module:model/UsersListDto} The populated <code>UsersListDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsersListDto();

            if (data.hasOwnProperty('usersIds')) {
                obj['usersIds'] = ApiClient.convertToType(data['usersIds'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsersListDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsersListDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UsersListDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['usersIds'])) {
            throw new Error("Expected the field `usersIds` to be an array in the JSON data but got " + data['usersIds']);
        }

        return true;
    }


}

UsersListDto.RequiredProperties = ["usersIds"];

/**
 * Lista de IDs de usuarios
 * @member {Array.<Number>} usersIds
 */
UsersListDto.prototype['usersIds'] = undefined;






export default UsersListDto;

