/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Usuario from './Usuario';

/**
 * The UsuarioList model module.
 * @module model/UsuarioList
 * @version 1.0
 */
class UsuarioList {
    /**
     * Constructs a new <code>UsuarioList</code>.
     * @alias module:model/UsuarioList
     */
    constructor() { 
        
        UsuarioList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsuarioList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsuarioList} obj Optional instance to populate.
     * @return {module:model/UsuarioList} The populated <code>UsuarioList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsuarioList();

            if (data.hasOwnProperty('usuarios')) {
                obj['usuarios'] = ApiClient.convertToType(data['usuarios'], [Usuario]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UsuarioList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UsuarioList</code>.
     */
    static validateJSON(data) {
        if (data['usuarios']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['usuarios'])) {
                throw new Error("Expected the field `usuarios` to be an array in the JSON data but got " + data['usuarios']);
            }
            // validate the optional field `usuarios` (array)
            for (const item of data['usuarios']) {
                Usuario.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Usuario>} usuarios
 */
UsuarioList.prototype['usuarios'] = undefined;






export default UsuarioList;

