/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventoOrganizacionDto from './EventoOrganizacionDto';

/**
 * The VoluntarioEventoDto model module.
 * @module model/VoluntarioEventoDto
 * @version 1.0
 */
class VoluntarioEventoDto {
    /**
     * Constructs a new <code>VoluntarioEventoDto</code>.
     * @alias module:model/VoluntarioEventoDto
     * @param idVoluntario {String} 
     * @param nombre {String} 
     * @param apellido {String} 
     * @param email {String} 
     * @param organizacion {module:model/EventoOrganizacionDto} 
     */
    constructor(idVoluntario, nombre, apellido, email, organizacion) { 
        
        VoluntarioEventoDto.initialize(this, idVoluntario, nombre, apellido, email, organizacion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, idVoluntario, nombre, apellido, email, organizacion) { 
        obj['idVoluntario'] = idVoluntario;
        obj['nombre'] = nombre;
        obj['apellido'] = apellido;
        obj['email'] = email;
        obj['organizacion'] = organizacion;
    }

    /**
     * Constructs a <code>VoluntarioEventoDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VoluntarioEventoDto} obj Optional instance to populate.
     * @return {module:model/VoluntarioEventoDto} The populated <code>VoluntarioEventoDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VoluntarioEventoDto();

            if (data.hasOwnProperty('idVoluntario')) {
                obj['idVoluntario'] = ApiClient.convertToType(data['idVoluntario'], 'String');
            }
            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('apellido')) {
                obj['apellido'] = ApiClient.convertToType(data['apellido'], 'String');
            }
            if (data.hasOwnProperty('telefono')) {
                obj['telefono'] = ApiClient.convertToType(data['telefono'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('organizacion')) {
                obj['organizacion'] = EventoOrganizacionDto.constructFromObject(data['organizacion']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VoluntarioEventoDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VoluntarioEventoDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of VoluntarioEventoDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['idVoluntario'] && !(typeof data['idVoluntario'] === 'string' || data['idVoluntario'] instanceof String)) {
            throw new Error("Expected the field `idVoluntario` to be a primitive type in the JSON string but got " + data['idVoluntario']);
        }
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }
        // ensure the json data is a string
        if (data['apellido'] && !(typeof data['apellido'] === 'string' || data['apellido'] instanceof String)) {
            throw new Error("Expected the field `apellido` to be a primitive type in the JSON string but got " + data['apellido']);
        }
        // ensure the json data is a string
        if (data['telefono'] && !(typeof data['telefono'] === 'string' || data['telefono'] instanceof String)) {
            throw new Error("Expected the field `telefono` to be a primitive type in the JSON string but got " + data['telefono']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // validate the optional field `organizacion`
        if (data['organizacion']) { // data not null
          EventoOrganizacionDto.validateJSON(data['organizacion']);
        }

        return true;
    }


}

VoluntarioEventoDto.RequiredProperties = ["idVoluntario", "nombre", "apellido", "email", "organizacion"];

/**
 * @member {String} idVoluntario
 */
VoluntarioEventoDto.prototype['idVoluntario'] = undefined;

/**
 * @member {String} nombre
 */
VoluntarioEventoDto.prototype['nombre'] = undefined;

/**
 * @member {String} apellido
 */
VoluntarioEventoDto.prototype['apellido'] = undefined;

/**
 * @member {String} telefono
 */
VoluntarioEventoDto.prototype['telefono'] = undefined;

/**
 * @member {String} email
 */
VoluntarioEventoDto.prototype['email'] = undefined;

/**
 * @member {module:model/EventoOrganizacionDto} organizacion
 */
VoluntarioEventoDto.prototype['organizacion'] = undefined;






export default VoluntarioEventoDto;

