/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentada);
  }
}(this, function(expect, ApiDocumentada) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentada.DonacionTransferencia();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DonacionTransferencia', function() {
    it('should create an instance of DonacionTransferencia', function() {
      // uncomment below and update the code to test DonacionTransferencia
      //var instance = new ApiDocumentada.DonacionTransferencia();
      //expect(instance).to.be.a(ApiDocumentada.DonacionTransferencia);
    });

    it('should have the property categoria (base name: "categoria")', function() {
      // uncomment below and update the code to test the property categoria
      //var instance = new ApiDocumentada.DonacionTransferencia();
      //expect(instance).to.be();
    });

    it('should have the property descripcion (base name: "descripcion")', function() {
      // uncomment below and update the code to test the property descripcion
      //var instance = new ApiDocumentada.DonacionTransferencia();
      //expect(instance).to.be();
    });

    it('should have the property cantidad (base name: "cantidad")', function() {
      // uncomment below and update the code to test the property cantidad
      //var instance = new ApiDocumentada.DonacionTransferencia();
      //expect(instance).to.be();
    });

  });

}));
