/**
 * Api Documentada
 * Documentación de la API de ejemplo con Flask + gRPC
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentada);
  }
}(this, function(expect, ApiDocumentada) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentada.VoluntarioEventoDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VoluntarioEventoDto', function() {
    it('should create an instance of VoluntarioEventoDto', function() {
      // uncomment below and update the code to test VoluntarioEventoDto
      //var instance = new ApiDocumentada.VoluntarioEventoDto();
      //expect(instance).to.be.a(ApiDocumentada.VoluntarioEventoDto);
    });

    it('should have the property idVoluntario (base name: "idVoluntario")', function() {
      // uncomment below and update the code to test the property idVoluntario
      //var instance = new ApiDocumentada.VoluntarioEventoDto();
      //expect(instance).to.be();
    });

    it('should have the property nombre (base name: "nombre")', function() {
      // uncomment below and update the code to test the property nombre
      //var instance = new ApiDocumentada.VoluntarioEventoDto();
      //expect(instance).to.be();
    });

    it('should have the property apellido (base name: "apellido")', function() {
      // uncomment below and update the code to test the property apellido
      //var instance = new ApiDocumentada.VoluntarioEventoDto();
      //expect(instance).to.be();
    });

    it('should have the property telefono (base name: "telefono")', function() {
      // uncomment below and update the code to test the property telefono
      //var instance = new ApiDocumentada.VoluntarioEventoDto();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new ApiDocumentada.VoluntarioEventoDto();
      //expect(instance).to.be();
    });

    it('should have the property organizacion (base name: "organizacion")', function() {
      // uncomment below and update the code to test the property organizacion
      //var instance = new ApiDocumentada.VoluntarioEventoDto();
      //expect(instance).to.be();
    });

  });

}));
